# Generated by Django 4.2.11 on 2024-03-28 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("med_alert_app", "0003_document"),
    ]

    operations = [
        migrations.RemoveField(model_name="document", name="upload_time",),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("been_viewed", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("offenders_names", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("date_time_of_offense", models.DateField()),
                ("offense_description", models.TextField(blank=True)),
                ("action_desired", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="report",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="med_alert_app.report",
            ),
        ),
    ]
