# Generated by Django 4.2.11 on 2024-03-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_alert_app', '0005_alter_report_date_time_of_offense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_time_of_offense',
            field=models.DateTimeField(blank=True),
        ),
    ]
