# Generated by Django 4.2.11 on 2024-03-29 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("med_alert_app", "0007_alter_report_date_time_of_offense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="date_time_of_offense",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
