# Generated by Django 4.2.11 on 2024-03-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med_alert_app", "0008_alter_report_date_time_of_offense_alter_report_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="resolved_action",
            field=models.TextField(blank=True, null=True),
        ),
    ]
