# Generated by Django 4.2.11 on 2024-04-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med_alert_app", "0010_report_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="upload",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
