# Generated by Django 4.2.11 on 2024-04-16 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("med_alert_app", "0011_alter_document_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteadmin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siteadmin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
