# Generated by Django 4.2.11 on 2024-04-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med_alert_app", "0012_alter_siteadmin_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="upload_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
